#!/usr/bin/env bash
# Simple deployment script for jpkindia.org static Vite build
# Usage (first time as root or via sudo):
#   sudo bash deploy/deploy_static.sh --domain jpkindia.org --with-cert --api-port 5000
# Subsequent updates (frontend only):
#   sudo bash deploy/deploy_static.sh --update-only

set -euo pipefail
DOMAIN="jpkindia.org"
WITH_CERT=0
UPDATE_ONLY=0
WEB_ROOT="/var/www/jpkindia"
BASE_PATH="/"  # override with --base-path
API_PORT="5000" # override with --api-port

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2;;
    --with-cert) WITH_CERT=1; shift;;
    --update-only) UPDATE_ONLY=1; shift;;
    --base-path) BASE_PATH="$2"; shift 2;;
    --api-port) API_PORT="$2"; shift 2;;
    *) echo "Unknown arg: $1"; exit 1;;
  esac
done

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$PROJECT_ROOT/dist"
NGINX_CONF_AVAIL="/etc/nginx/sites-available/${DOMAIN%%:*}"
NGINX_CONF_ENABLED="/etc/nginx/sites-enabled/${DOMAIN%%:*}"

if [[ $UPDATE_ONLY -eq 0 ]]; then
  echo "==> Building project (Vite) with BASE_PATH=$BASE_PATH"
  (cd "$PROJECT_ROOT" && BASE_PATH="$BASE_PATH" npm run build)
else
  if [[ ! -d "$DIST_DIR" ]]; then
    echo "dist/ missing; cannot --update-only. Run without --update-only first." >&2
    exit 1
  fi
fi

# Prepare web root
mkdir -p "$WEB_ROOT"
chown -R www-data:www-data "$WEB_ROOT" || true

# Sync new build (atomic-ish deploy via temp dir)
TMP_SYNC="${WEB_ROOT}.new"
rm -rf "$TMP_SYNC"
mkdir -p "$TMP_SYNC"
rsync -a --delete "$DIST_DIR"/ "$TMP_SYNC"/
# Move into place
rsync -a --delete "$TMP_SYNC"/ "$WEB_ROOT"/
rm -rf "$TMP_SYNC"
chown -R www-data:www-data "$WEB_ROOT"

if [[ $UPDATE_ONLY -eq 0 ]]; then
  echo "==> Writing nginx config (HTTP) with API proxy to $NGINX_CONF_AVAIL"
  cat > "$NGINX_CONF_AVAIL" <<CONF
# Auto-generated by deploy_static.sh
# FRONTEND: ${WEB_ROOT}
# API: http://127.0.0.1:${API_PORT}/ mapped at /api/

map \$http_upgrade \$connection_upgrade { default upgrade; '' close; }

server {
  listen 80;
  server_name ${DOMAIN} www.${DOMAIN};
  root ${WEB_ROOT};
  index index.html;

  # --- API reverse proxy ---
  location ^~ /api/ {
    proxy_pass http://127.0.0.1:${API_PORT}/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_buffering off;
    client_max_body_size 25m;

    # CORS (adjust as needed)
    add_header Access-Control-Allow-Origin "https://$DOMAIN" always;
    add_header Access-Control-Allow-Credentials "true" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
    if (\$request_method = OPTIONS) { return 204; }
  }

  # --- Frontend SPA ---
  location / {
    try_files \$uri /index.html;
  }

  # Static asset caching
  location ~* \.(?:js|css|woff2?|ttf|eot|ico|svg|png|jpg|jpeg|gif)$ {
    try_files \$uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header X-XSS-Protection "1; mode=block";
  add_header Cross-Origin-Opener-Policy same-origin;
  add_header Cross-Origin-Resource-Policy same-origin;

  access_log /var/log/nginx/${DOMAIN}.access.log;
  error_log  /var/log/nginx/${DOMAIN}.error.log;
}
CONF
  ln -sf "$NGINX_CONF_AVAIL" "$NGINX_CONF_ENABLED"
  echo "==> Testing nginx config"
  nginx -t
  echo "==> Reloading nginx"
  systemctl reload nginx
  echo "NOTE: If HTTPS already configured, replicate the /api/ block inside the SSL server block or re-run certbot afterward."
fi

if [[ $WITH_CERT -eq 1 ]]; then
  if ! command -v certbot >/dev/null 2>&1; then
    echo "Installing certbot (snap)";
    apt update && apt install -y snapd || true
    snap install core && snap refresh core
    snap install --classic certbot
    ln -sf /snap/bin/certbot /usr/bin/certbot
  fi
  echo "==> Obtaining/renewing certificate via certbot"
  certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --redirect --non-interactive --agree-tos -m admin@${DOMAIN} || {
    echo "Certbot failed" >&2; exit 1; }
fi

echo "==> Deployment complete"
# NOTE: Existing HTTPS nginx config detected previously; ensure /api/ block is added manually to SSL server.
